spring:
  application:
    name: marketplace
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 21MB

marketplace:
  outbox:
    relay:
      fixed-delay-ms: 1000
  import:
    storage-dir: ${java.io.tmpdir}/marketplace-imports
